### ISSUE TITLE
Analysis Page MVP

### ISSUE THREAD

**Issue by rknizzle** [rknizzle/propermesh-view#18]
Basic sketch of where each component will sit: https://www.figma.com/file/qVQrVqEflysUjbrTDZggFB/Analysis-Page?type=design&node-id=0%3A1&mode=design&t=GCpunY995Oemhjm7-1

I think there will be a top level AnalysisPage component or something like that and then it will use each of these components inside of it:

- [x] Upload Part button -- https://github.com/rknizzle/propermesh-view/issues/19
- [x] List parts button -- https://github.com/rknizzle/propermesh-view/issues/20
- [x] 3D model viewer -- https://github.com/rknizzle/propermesh-view/issues/3
  - Just get a very basic viewer for now with zooming and rotating and maybe a loader for each supported file (you can skip all the other loaders for now if you want to move onto something else. Not super important.)
- [x] Units selector -- https://github.com/rknizzle/propermesh-view/issues/28
- [x] Geometry Analysis box -- https://github.com/rknizzle/propermesh-view/issues/21
- [x] Thickness analysis Box -- https://github.com/rknizzle/propermesh-view/issues/29
- [x] Style analysis page for different sized screens
- [x] View thickness visualization file in 3d viewer -- TODO
- [ ] Extra info section -- TODO link to specific PR

**Comment by rknizzle** [comment]
@ErikAmerico Ill use this as the main info area for the analysis page. I'll link to all the more specific issues for each of the components here
